spring:
    h2:
      console:
        enabled: true
        path: /h2-console

    datasource:
      url: jdbc:h2:mem:jesslog
      username: sa
      password:
      driver-class-name: org.h2.Driver